# Generated by Django 2.0.1 on 2018-08-16 06:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsTransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=255)),
                ('income', models.FloatField(null=True)),
                ('outcome', models.FloatField(null=True)),
                ('desc', models.CharField(default='', max_length=255, null=True)),
                ('balance', models.FloatField()),
                ('other', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='StatsTransactionRecordOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=50)),
                ('prop', models.CharField(max_length=50, null=True)),
                ('extra', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StatsTransactionRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Taizhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditId', models.UUIDField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=255)),
                ('asset', models.CharField(max_length=255)),
                ('upstream', models.CharField(max_length=255)),
                ('upstream_dunwei', models.DecimalField(decimal_places=2, max_digits=19)),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('kaipiao_dunwei', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('upstream_jiesuan_price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('downstream', models.CharField(max_length=255)),
                ('downstream_dunwei', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('kaipiao_dunwei_trade', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('downstream_jiesuan_price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('shangyou_zijin_zhanya', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('shangyou_kuchun_liang', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('shangyou_kuchun_yuji_danjia', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaizhangOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=50)),
                ('prop', models.CharField(max_length=50, null=True)),
                ('extra', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Taizhang')),
            ],
        ),
    ]
