# Generated by Django 2.0.1 on 2018-07-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('shareholder', models.CharField(max_length=255)),
                ('faren', models.CharField(max_length=255)),
                ('capital', models.FloatField()),
                ('year', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
