# Generated by Django 2.0.1 on 2018-07-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditactivity',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditactivity',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('processing', 'processing'), ('approved', 'approved'), ('rejected', 'rejected'), ('rejected', 'cancelled')], default='draft', max_length=20),
        ),
    ]
