# Generated by Django 2.0.1 on 2018-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taizhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditId', models.UUIDField(null=True)),
                ('date', models.CharField(max_length=255)),
                ('asset', models.CharField(max_length=255)),
                ('upstream', models.CharField(max_length=255)),
                ('upstream_dunwei', models.DecimalField(decimal_places=10, max_digits=19)),
                ('buyPrice', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kaipiao_dunwei', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('upstream_jiesuan_price', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('downstream', models.CharField(max_length=255)),
                ('downstream_dunwei', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sellPrice', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kaipiao_dunwei_trade', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('downstream_jiesuan_price', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('cangchu_gongsi', models.CharField(max_length=255, null=True)),
                ('shangyou_zijin_zhanya', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('xiayou_zijin_zhanya', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('fukuan_riqi', models.CharField(max_length=255, null=True)),
                ('fukuan_jine', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('shoukuan_riqi', models.CharField(max_length=255, null=True)),
                ('shoukuan_jine', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('jiesuan_zhouqi', models.CharField(max_length=255, null=True)),
                ('nianhua_maolilv', models.CharField(max_length=255, null=True)),
                ('kuchun_shangyou_gongfang', models.CharField(max_length=255, null=True)),
                ('shangyou_kuchun_hetongshu', models.CharField(max_length=255, null=True)),
                ('shangyou_kuchun_fukuan_riqi', models.CharField(max_length=255, null=True)),
                ('shangyou_kuchun_fukuan_jine', models.CharField(max_length=255, null=True)),
                ('shangyou_kuchun_liang', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('shangyou_kuchun_yuji_danjia', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('xiayou_kuchun_hetongshu', models.CharField(max_length=255, null=True)),
                ('xiayou_kuchun_shoukuan_riqi', models.CharField(max_length=255, null=True)),
                ('xiayou_kuchun_shoukuan_jine', models.CharField(max_length=255, null=True)),
                ('xiayou_kuchun_yugu_lirun', models.CharField(max_length=255, null=True)),
                ('xiayou_kuchun_shiji_lirun', models.CharField(max_length=255, null=True)),
                ('kuchun_huowu', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
