# Generated by Django 2.0.1 on 2018-08-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statstransactionrecord_statstransactionrecordops_taizhang_taizhangops'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255, null=True)),
                ('yewuliang', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='StatsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaizhangStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255)),
                ('asset', models.CharField(max_length=255, null=True)),
                ('xiaoshoue', models.DecimalField(decimal_places=2, max_digits=19)),
                ('lirune', models.DecimalField(decimal_places=2, max_digits=19)),
                ('kuchun_liang', models.DecimalField(decimal_places=2, max_digits=19)),
                ('zijin_zhanya', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('startDayOfWeek', models.CharField(max_length=255, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=19)),
                ('outcome', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finaccount',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionstat',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FinAccount'),
        ),
    ]
