# Generated by Django 2.0.1 on 2018-08-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statstransactionrecord_statstransactionrecordops_taizhang_taizhangops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_kuchun_liang',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_kuchun_yuji_danjia',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_zijin_zhanya',
        ),
    ]
