# Generated by Django 2.0.1 on 2018-08-12 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taizhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='taizhang',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taizhang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taizhang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
