# Generated by Django 2.0.1 on 2018-08-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180812_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taizhang',
            name='buyPrice',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='downstream_dunwei',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='downstream_jiesuan_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='fukuan_jine',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='kaipiao_dunwei',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='kaipiao_dunwei_trade',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='sellPrice',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shangyou_kuchun_liang',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shangyou_kuchun_yuji_danjia',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shangyou_zijin_zhanya',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shoukuan_jine',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='upstream_dunwei',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='upstream_jiesuan_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='xiayou_zijin_zhanya',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
