# Generated by Django 2.0.1 on 2018-08-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180818_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstat',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='buyPrice',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='downstream_dunwei',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='downstream_jiesuan_price',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='kaipiao_dunwei',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='kaipiao_dunwei_trade',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='sellPrice',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shangyou_kuchun_liang',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shangyou_kuchun_yuji_danjia',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='shangyou_zijin_zhanya',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='upstream_dunwei',
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='upstream_jiesuan_price',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
    ]
