# Generated by Django 2.0.1 on 2018-08-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180816_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='taizhang',
            name='shangyou_kuchun_jine',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='taizhang',
            name='shangyou_kuchun_liang',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='taizhang',
            name='shangyou_kuchun_yuji_danjia',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='taizhang',
            name='shangyou_zijin_zhanya',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
