# Generated by Django 2.0.1 on 2018-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180816_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_kuchun_jine',
        ),
        migrations.AddField(
            model_name='taizhang',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
