# Generated by Django 2.0.1 on 2018-08-13 00:07

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180812_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaizhangOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=50)),
                ('prop', models.CharField(max_length=50, null=True)),
                ('extra', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='cangchu_gongsi',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='fukuan_jine',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='fukuan_riqi',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='jiesuan_zhouqi',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='kuchun_huowu',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='kuchun_shangyou_gongfang',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='nianhua_maolilv',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_kuchun_fukuan_jine',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_kuchun_fukuan_riqi',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shangyou_kuchun_hetongshu',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shoukuan_jine',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='shoukuan_riqi',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='xiayou_kuchun_hetongshu',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='xiayou_kuchun_shiji_lirun',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='xiayou_kuchun_shoukuan_jine',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='xiayou_kuchun_shoukuan_riqi',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='xiayou_kuchun_yugu_lirun',
        ),
        migrations.RemoveField(
            model_name='taizhang',
            name='xiayou_zijin_zhanya',
        ),
        migrations.AddField(
            model_name='taizhangops',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Taizhang'),
        ),
    ]
