# Generated by Django 2.0.1 on 2018-08-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('hkd', '港币'), ('dollar', '人民币')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('c1', '大型生产商/终端用户'), ('c2', '中型生产商/终端、大型生产商直属贸易商、大型贸易商'), ('c3', '小型生产商/终端、实体贸易商'), ('c4', '中小型纯贸易商')], max_length=255),
        ),
    ]
