# Generated by Django 2.0.1 on 2018-09-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180821_0252'),
    ]

    operations = [
    ]
