# Generated by Django 2.0.1 on 2018-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180816_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taizhang',
            name='company',
            field=models.CharField(default='中阅和瑞', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='downstream',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
