# Generated by Django 2.0.1 on 2018-08-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180802_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaccount',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
