# Generated by Django 2.0.1 on 2018-08-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_finaccount_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsTransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=255)),
                ('income', models.FloatField(null=True)),
                ('outcome', models.FloatField(null=True)),
                ('desc', models.CharField(default='', max_length=255)),
                ('balance', models.FloatField()),
                ('other', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
    ]
