# Generated by Django 2.0.1 on 2018-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_finaccount_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditactivity',
            name='taskState',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
