# Generated by Django 2.0.1 on 2018-08-06 09:35

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statstransactionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsTransactionRecordOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=50)),
                ('extra', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='statstransactionrecord',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statstransactionrecordops',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StatsTransactionRecord'),
        ),
    ]
