# Generated by Django 2.0.1 on 2018-09-14 01:55

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180827_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('interface', models.CharField(max_length=255)),
                ('interfacePosition', models.CharField(max_length=255)),
                ('interfacePhone', models.CharField(max_length=255)),
                ('meetTime', models.DateTimeField()),
                ('meetPlace', models.CharField(max_length=255)),
                ('member', models.CharField(max_length=255, null=True)),
                ('otherMember', models.CharField(max_length=255, null=True)),
                ('otherMemberPosition', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(null=True)),
                ('next', models.TextField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FinCustomerOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=50)),
                ('prop', models.CharField(max_length=50, null=True)),
                ('extra', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FinCustomer')),
            ],
        ),
    ]
