# Generated by Django 2.0.1 on 2018-10-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='apn_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deviceId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
