# Generated by Django 2.0.1 on 2018-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181011_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditactivity',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
    ]
