# Generated by Django 2.0.1 on 2019-01-18 07:00

from django.db import migrations
from core.models import *


def rename_owner(app, schema_editor):
    Position.objects.filter(code='owner').update(name='总经理')
    Department.objects.filter(code='jinrong').update(name='金融中心')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20181102_0754'),
    ]

    operations = [
        migrations.RunPython(rename_owner),
    ]
