# Generated by Django 2.0.1 on 2018-09-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_memo'),
        ('core', '0008_auto_20180919_0849'),
    ]

    operations = [
    ]
