# Generated by Django 2.0.1 on 2019-03-18 08:28

from django.db import migrations

from core import specs
from core.models_v1 import *
from core.management.commands import prepareData


def add_rongzi_audit(apps, schema_editor):
    pos_owner = PositionLegacy.objects.filter(code='owner').first()
    if pos_owner is None:
        # prepare data
        cmd = prepareData.Command()
        cmd.handle()
        pos_owner = PositionLegacy.objects.get(code='owner')

    dep = DepartmentLegacy.objects.filter(code='jinrong').first()
    if dep is None:
        dep = DepartmentLegacy.objects.create(code='jinrong', name='金融中心')
        DepPosLegacy.objects.create(pos=pos_owner, dep=dep)

    specs.createAuditConfig(spec='law.rongzitikuan:\
                                jinrong.owner->\
                                fin.fin_accountant->\
                                fin.owner->\
                                root.ceo...')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_add_positions'),
    ]

    operations = [
        migrations.RunPython(add_rongzi_audit),
    ]
