# Generated by Django 2.0.1 on 2019-03-18 08:28

from django.db import migrations

from core import specs
from core.models import *
from core.management.commands import prepareData


def add_audit_flow(apps, schema_editor):
    specs.createAuditConfig(spec='law.biz_contract_no_risk:\
                            fin.fin_accountant->\
                            dazong.owner->\
                            fin.owner...')

    specs.createAuditConfig(spec='law.biz_contract_risk:\
                            fin.fin_accountant->\
                            dazong.owner->\
                            fin.owner->\
                            root.ceo...')

    specs.createAuditConfig(spec='fin.money_no_risk:\
                            fin.fin_accountant->\
                            dazong.owner->\
                            fin.owner...')

    specs.createAuditConfig(spec='fin.money_risk:\
                            fin.fin_accountant->\
                            dazong.owner->\
                            fin.owner->\
                            root.ceo...')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_auto_20190318_0828'),
    ]

    operations = [
        migrations.RunPython(add_audit_flow),
    ]
