# Generated by Django 2.0.1 on 2018-09-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_v1_audit_config_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditactivityconfig',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditactivityconfigstep',
            name='assigneePosition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Position'),
        ),
    ]
