# Generated by Django 2.0.1 on 2019-04-21 14:49

from django.db import migrations

from core import specs


def update_audit_flow(apps, schema_editor):
    specs.updateAuditConfig(spec='law.biz_contract_no_risk:\
                            fin.fin_accountant->\
                            _.owner->\
                            fin.owner...')

    specs.updateAuditConfig(spec='law.biz_contract_risk:\
                            fin.fin_accountant->\
                            _.owner->\
                            fin.owner->\
                            root.ceo...')

    specs.updateAuditConfig(spec='fin.money_no_risk:\
                            fin.fin_accountant->\
                            _.owner->\
                            fin.owner...')

    specs.updateAuditConfig(spec='fin.money_risk:\
                            fin.fin_accountant->\
                            _.owner->\
                            fin.owner->\
                            root.ceo...')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_auto_20190416_0718'),
    ]

    operations = [
        migrations.RunPython(update_audit_flow),
    ]
