# Generated by Django 2.0.1 on 2018-09-27 08:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180927_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditactivity',
            name='config_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
