# Generated by Django 2.0.1 on 2019-04-24 02:17

from django.db import migrations

from core import specs


def update_audit_flow(apps, schema_editor):
    specs.updateAuditConfig(spec='law.biz_contract_no_risk:\
                            fin.fin_accountant->\
                            fin.owner...')

    specs.updateAuditConfig(spec='law.biz_contract_risk:\
                            fin.fin_accountant->\
                            _.owner->\
                            root.ceo...')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190421_1449'),
    ]

    operations = [
        migrations.RunPython(update_audit_flow),
    ]
