# Generated by Django 2.0.1 on 2018-09-19 09:45

from django.db import migrations, transaction
from core.models import *
from core.management.commands.prepareData import Command
from core import specs_v3


class Migrator():
    def migrateCostAudit(self):
        subtypes = ['cost_lte_5000', 'cost_gt_5000']
        for index, t in enumerate(subtypes):
            audit = AuditActivityConfig.objects.get(subtype=t)
            audit.subtype = 'cost'
            audit.priority = index + 1
            _, condition, value = t.split('_')
            audit.conditions = [
                {'prop': 'amount', 'condition': condition, 'value': int(value)}
            ]
            audit.save()

    def migrateLoanAudit(self):
        subtypes = ['loan_lte_5000', 'loan_gt_5000']
        for index, t in enumerate(subtypes):
            audit = AuditActivityConfig.objects.get(subtype=t)
            audit.subtype = 'loan'
            audit.priority = index + 1
            _, condition, value = t.split('_')
            audit.conditions = [
                {'prop': 'amount', 'condition': condition, 'value': int(value)}
            ]
            audit.save()

    def migrateTravelAudit(self):
        subtypes = ['travel_lte_5000', 'travel_gt_5000']
        for index, t in enumerate(subtypes):
            audit = AuditActivityConfig.objects.get(subtype=t)
            audit.subtype = 'travel'
            audit.priority = index + 1
            _, condition, value = t.split('_')
            audit.conditions = [
                {'prop': 'amount', 'condition': condition, 'value': int(value)}
            ]
            audit.save()

    def migrateMoneyAudit(self):

        audit = AuditActivityConfig.objects.get(subtype='money_caigou_or_other_lte_5k')
        audit.conditions = [
            {'prop': 'amount', 'condition': 'lte', 'value': 5000},
            {'prop': 'info.type', 'condition': 'eq', 'value': ['caigou', 'other']}
        ]
        audit.priority = 1
        audit.subtype = 'money'
        audit.save()

        audit = AuditActivityConfig.objects.get(subtype='money_caigou_or_other')
        audit.conditions = [
            {'prop': 'info.type', 'condition': 'eq', 'value': ['caigou', 'other']}
        ]
        audit.priority = 2
        audit.subtype = 'money'
        audit.save()

        audit = AuditActivityConfig.objects.get(subtype='money_lte_50k')
        audit.priority = 3
        audit.conditions = [
            {'prop': 'amount', 'condition': 'lte', 'value': 50 * 1000}
        ]
        audit.subtype = 'money'
        audit.save()

        audit = AuditActivityConfig.objects.get(subtype='money_gt_50k')
        audit.priority = 4
        audit.conditions = [
            {'prop': 'amount', 'condition': 'gt', 'value': 50 * 1000}
        ]
        audit.subtype = 'money'
        audit.save()

    def migratePurchaseAudit(self):
        subtypes = ['purchase_lte_5000', 'purchase_gt_5000']
        for index, t in enumerate(subtypes):
            audit = AuditActivityConfig.objects.get(subtype=t)
            audit.subtype = 'purchase'
            audit.priority = index + 1
            _, condition, value = t.split('_')
            audit.conditions = [
                {'prop': 'amount', 'condition': condition, 'value': int(value)}
            ]
            audit.save()

    def migrateOpenAccountAudit(self):
        audit = AuditActivityConfig.objects.get(subtype='open_account')
        audit.priority = 0
        audit.fallback = True
        audit.save()

    def migrateBizContractAudit(self):
        audit = AuditActivityConfig.objects.get(subtype='biz_contract')
        audit.subtype = 'biz'
        audit.priority = 0
        audit.fallback = True
        audit.save()

    def migrateFnContractAudit(self):
        audit = AuditActivityConfig.objects.get(subtype='fn_contract')
        audit.subtype = 'fn'
        audit.priority = 0
        audit.fallback = True
        audit.save()

        audit = AuditActivityConfig.objects.get(subtype='fn_contract_zero')
        audit.subtype = 'fn'
        audit.conditions = [
            {'prop': 'amount', 'condition': 'eq', 'value': 0}
        ]
        audit.priority = 1
        audit.fallback = False
        audit.save()

    def migrate(self):
        # migrate v1 audit configs to v3

        with transaction.atomic():
            # fin audits
            self.migrateCostAudit()
            self.migrateLoanAudit()
            self.migrateMoneyAudit()
            self.migratePurchaseAudit()
            self.migrateTravelAudit()
            self.migrateOpenAccountAudit()

            # law audits
            self.migrateBizContractAudit()
            self.migrateFnContractAudit()


def prepareV1DataIfNeed(apps, schema_editor):
    with transaction.atomic():
        config = AuditActivityConfig.objects \
            .filter(subtype='cost_lte_5000') \
            .first()
        if config != None:
            return

        cmd = Command()
        cmd.handle()


def upgradeToV3(apps, schema_editor):
    m = Migrator()
    m.migrate()


def prepareV3AuditCofigurationData(apps, schema_editor):
    Configuration.objects.create(
        key='audits',
        value={
            'categories': ['fin', 'law', 'hr'],
            'audits': [
                {'subtype': 'cost', 'name': '费用报销', 'category': 'fin', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'loan', 'name': '借款申请', 'category': 'fin', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'money', 'name': '用款申请', 'category': 'fin', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'open_account', 'name': '银行开户', 'category': 'fin', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'travel', 'name': '差旅报销', 'category': 'fin', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},

                {'subtype': 'biz', 'name': '业务合同会签', 'category': 'law', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'fn', 'name': '职能合同会签', 'category': 'law', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},

                {'subtype': 'zhuanzheng', 'name': '员工转正评定', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'transfer', 'name': '内部调动', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'leave', 'name': '离职申请', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'leave_handover', 'name': '离职交接', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},

                {'subtype': 'qingjia', 'name': '请假申请', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'chuchai', 'name': '出差申请', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'kaoqin_yichang', 'name': '考勤异常申请', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},

                {'subtype': 'yinjian_kezhi', 'name': '印鉴刻制申请', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
                {'subtype': 'dangan_jiechu', 'name': '业务档案原件借出', 'category': 'hr', 'hasTask': True, 'enabled': True,
                 'updated_at': timezone.now()},
            ]
        }
    )

    # 内部调动默认审批流程
    specs_v3.createAuditConfig(spec='hr.transfer:_.owner->hr.owner->root.ceo', fallback=True)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_auto_20181014_0821'),
    ]

    operations = [
        migrations.RunPython(prepareV1DataIfNeed),
        migrations.RunPython(upgradeToV3),
        migrations.RunPython(prepareV3AuditCofigurationData)
    ]
