# Generated by Django 2.0.1 on 2019-04-26 00:00

from django.db import migrations

from core import specs


def add_money_transfer_audit_flow(apps, schema_editor):
    specs.createAuditConfig(spec='fin.money_transfer:\
                                fin.fin_accountant->\
                                fin.owner->\
                                root.ceo...')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_auto_20190424_0217'),
    ]

    operations = [
        migrations.RunPython(add_money_transfer_audit_flow),
    ]
