# Generated by Django 2.0.1 on 2019-04-27 14:04

from django.db import migrations
from core import specs


def update_biz_audit_flow(apps, schema_editor):
    specs.updateAuditConfig(spec='fin.money_transfer:fin.fin_accountant->fin.owner...')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_auto_20190426_0020'),
    ]

    operations = [
        migrations.RunPython(update_biz_audit_flow),
    ]
