# Generated by Django 2.0.1 on 2019-05-05 23:49

from django.db import migrations
from core.models import Department, Position, DepPos
from core.models_v1 import *


def add_new_department(apps, schema_editor):
    hr = DepartmentLegacy.objects.get(code='hr')
    dep = DepartmentLegacy.objects.create(code='hr-risk', name='风险合规部', parent=hr)
    pos = PositionLegacy.objects.create(code='fuzongjian', name='副总监')
    DepPosLegacy.objects.create(dep=dep, pos=pos)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_auto_20190427_1404'),
    ]

    operations = [
        migrations.RunPython(add_new_department)
    ]
