# Generated by Django 2.0.1 on 2018-10-21 06:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181019_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstep',
            name='extra',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='state',
            field=models.CharField(choices=[('testing', 'testing'), ('normal', 'normal'), ('left', 'left')], default='testing', max_length=20),
        ),
    ]
