# Generated by Django 2.0.1 on 2019-05-04 15:56

import json
import os
from django.db import migrations

from core.models import *


def import_data(apps, schema_editor):
    dir_path = os.path.dirname(os.path.realpath(__file__))

    with open(dir_path + '/data.json') as f:
        data = json.load(f)
        for r in data:
            Taizhang.objects.create(**r)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_auto_20190504_1441'),
    ]

    operations = [
        migrations.RunPython(import_data),
    ]
