# Generated by Django 2.0.1 on 2019-05-04 15:59

from django.db import migrations
from core.models import *


def update_default_role(app, schema_editor):
    roleMember = Role.objects.filter(name='普通员工').first()
    if roleMember != None:
        roleMember.extra.append('launch_hr_audit')
        roleMember.save()

    roleSuperuser = Role.objects.filter(name='超级管理员').first()
    if roleSuperuser != None:
        roleSuperuser.extra.append('launch_hr_audit')

        # 员工档案管理
        roleSuperuser.extra.append('view_profiles')
        roleSuperuser.extra.append('add_profiles')
        roleSuperuser.extra.append('manage_profiles')

        # 部门职位管理
        roleSuperuser.extra.append('view_department')
        roleSuperuser.extra.append('add_department')
        roleSuperuser.extra.append('manage_department')
        roleSuperuser.extra.append('view_position')
        roleSuperuser.extra.append('add_position')
        roleSuperuser.extra.append('manage_position')
        roleSuperuser.extra.append('view_audit_category')
        roleSuperuser.extra.append('manage_audit_category')

        roleSuperuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_auto_20190504_1556'),
    ]

    operations = [
        migrations.RunPython(update_default_role),
    ]
