# Generated by Django 2.0.1 on 2019-05-10 03:03

# from core.models import *
# from core import specs
from django.db import migrations


def transfer(apps, schema_editor):
    pass
    # v3 nothing to do
    # print("\n")
    # print("\n")
    # print("=======transfer fin.fin_manager to fin.owner======")
    # print("")
    # pos_fin_manager = Position.objects.get(code='fin_manager')
    # department = Department.objects.get(code='fin')
    # DepPos.objects.create(dep=department, pos=pos_fin_manager)
    #
    # pos_owner = Position.objects.get(code='owner')
    # steps = AuditActivityConfigStep.objects.filter(assigneeDepartment=department, assigneePosition=pos_fin_manager)
    # for step in steps:
    #     config = AuditActivityConfig.objects.get(pk=step.config.pk)
    #     print('  Update audit flow {}.{}'.format(step.config.category, step.config.subtype))
    #     print('    previous:', specs.auditFlowToString(config))
    #     step.assigneePosition = pos_owner
    #     step.save()
    #     config = AuditActivityConfig.objects.get(pk=step.config.pk)
    #     print('     current:', specs.auditFlowToString(config))
    # print("")
    # print("=======transfer fin.fin_manager to fin.owner======")
    # print("\n")
    # print("\n")


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_transfer_audit_from_fin_owner_to_fin_manager_20190508_2359'),
    ]

    operations = [
        migrations.RunPython(transfer)
    ]
