# Generated by Django 2.0.1 on 2018-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181024_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='fincustomer',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
