# Generated by Django 2.0.1 on 2018-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181129_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='desc',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='skill_certs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='work_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
