# Generated by Django 2.0.1 on 2019-09-18 14:23

from django.db import migrations
from core.models import *


def addCustomAudit(apps, schema_editor):
    conf = Configuration.objects.filter(key='audits').first()
    conf.value['audits'].append({
        'subtype': 'custom',
        'name': '自定义审批',
        'category': 'hr',
        'enabled': True,
        'hasTask': True,
        'updated_at': timezone.now()
    })
    conf.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_auto_20190708_0029'),
    ]

    operations = [
        migrations.RunPython(addCustomAudit)
    ]
