# Generated by Django 2.0.1 on 2018-12-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20181217_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='weigh',
            new_name='weight',
        ),
    ]
