# Generated by Django 2.0.1 on 2018-12-28 08:19

import os
import json
from django.db import migrations

from core.models import Taizhang


def import_data(apps, schema_editor):
    dir_path = os.path.dirname(os.path.realpath(__file__))

    with open(dir_path + '/data.json') as f:
        data = json.load(f)
        for r in data:
            Taizhang.objects.create(**r)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0034_add_profile_info_data'),
    ]

    operations = [
        migrations.RunPython(import_data),
    ]
