# Generated by Django 2.0.1 on 2018-09-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180919_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditactivityconfig',
            old_name='default',
            new_name='fallback',
        ),
    ]
