# Generated by Django 2.0.1 on 2018-09-23 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20180923_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditactivityconfig',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditactivityconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditactivityconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
