# Generated by Django 2.0.1 on 2018-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auditactivity_config_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditactivityconfig',
            name='abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditactivityconfigstep',
            name='abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditactivity',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('processing', 'processing'), ('approved', 'approved'), ('rejected', 'rejected'), ('rejected', 'cancelled'), ('aborted', 'aborted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
