# Generated by Django 2.0.1 on 2018-10-19 08:10

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_migrate_v1_audit_config_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('testing', 'testing'), ('normal', 'normal'), ('left', 'left')], default='normal', max_length=20)),
                ('realname', models.CharField(max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('gender', models.IntegerField(default=0)),
                ('nation', models.CharField(max_length=255, null=True)),
                ('jiguan', models.CharField(max_length=255, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('join_at', models.DateTimeField(null=True)),
                ('positive_at', models.DateTimeField(null=True)),
                ('contract', models.CharField(max_length=255, null=True)),
                ('shebao', models.CharField(max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('contact_phone', models.CharField(max_length=255, null=True)),
                ('desc', models.CharField(max_length=255)),
                ('attachments', jsonfield.fields.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditstep',
            name='abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
