# Generated by Django 2.0.1 on 2018-11-15 09:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181106_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('for_all', models.BooleanField(default=True)),
                ('stick', models.BooleanField(default=False)),
                ('stick_duration', models.CharField(max_length=255, null=True)),
                ('attachments', jsonfield.fields.JSONField(null=True)),
                ('extra', jsonfield.fields.JSONField(null=True)),
                ('scope', jsonfield.fields.JSONField(null=True)),
                ('views', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Notification')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='notdep',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Notification'),
        ),
    ]
