# Generated by Django 2.0.1 on 2018-11-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_notification_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='shebao',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='birthday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='blood',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='contact_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='contact_relation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='contract_due',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='driving',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='education_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='graduation_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='hukou_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='hunyin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='id_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='join_at_contract',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='leave_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='leave_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='positive_at_contract',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='positive_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='rudang_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='spec',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='weigh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='work_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='work_transfer_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='zhengzhimianmao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
