# Generated by Django 2.0.1 on 2018-12-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20181217_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='avatar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
